[package]
name = "rep_interchange"
version = "0.1.0"
authors = ["Michael Hueschen <m@mhueschen.space>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combine = "4.5.2"
hdk = { path = "../../submodules/holochain/crates/hdk" }
serde = "1"

common = { path = "../common" }
rep_lang_concrete_syntax = { path = "../../submodules/rep_lang/rep_lang_concrete_syntax" }
rep_lang_core = { path = "../../submodules/rep_lang/rep_lang_core", features = ["hc"] }
rep_lang_runtime = { path = "../../submodules/rep_lang/rep_lang_runtime", features = ["hc"] }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
