[workspace]
members = [
  "crates/common",
  "crates/social_sensemaker",
  "crates/social_sensemaker_macros",

  # this keeps breaking due to not-so-actively maintained deps.
  # letting it bitrot for now.
  # "crates/frontend-tui",
]
