[package]
name = "frontend-tui"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "rlp"
path = "src/main.rs"

[dependencies]
combine = "4.5.2"
holochain_conductor_client = { git = "https://github.com/holochain/conductor-client-rust.git", rev = "da01edf2de86cdd929b8759f40058ed8ea7ecd11" }
rand = "0.8.4"
scrawl = "1.1.0"
termion = "1.5.6"
tui = "0.16.0"

common = { path = "../common" }
rep_lang_concrete_syntax = { path = "../../submodules/rep_lang/rep_lang_concrete_syntax", version = "0.1.0" }
rep_lang_core = { path = "../../submodules/rep_lang/rep_lang_core", version = "0.1.0", features = ["hc"] }
rep_lang_runtime = { path = "../../submodules/rep_lang/rep_lang_runtime", version = "0.1.0", features = ["hc"] }
