[package]
name = "common"
version = "0.1.0"
authors = ["Michael Hueschen <m@mhueschen.space>"]
edition = "2018"

[dependencies]
hdk = "0.0.116"
serde = "1"

rep_lang_concrete_syntax = { git = "https://github.com/sacredcapital/rep_lang.git", rev = "edac4320f6dc441ad2a873a32d986920fbc300b4" }
rep_lang_core = { git = "https://github.com/sacredcapital/rep_lang.git", rev = "edac4320f6dc441ad2a873a32d986920fbc300b4", features = ["hc"] }
rep_lang_runtime = { git = "https://github.com/sacredcapital/rep_lang.git", rev = "edac4320f6dc441ad2a873a32d986920fbc300b4", features = ["hc"] }
